---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: "instalamos el paquete httpd (apache)"
      package:
        name: httpd
        state: latest
    - name: "levantamos el servicio httpd y los dejamos enabled"
      service:
        name: httpd
        state: started
        enabled: yes
    - name: "creamos pagina de bienvenida en hosts"
      file:
        path: /var/www/html/index.html
        state: touch
    - name: "añadimos contenido al fichero de bienvenida"
      copy:
        content: "Hello world!"
        dest: /var/www/html/index.html
