---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: "creamos directorio /car/tmp/kk"
      file:
        path: /var/tmp/kk
        state: directory
      when: ansible_default_ipv4.address == "192.168.17.105"
